services:
  - type: web
    name: uems-backend
    env: docker
    region: oregon
    branch: main
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: uems-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: uems-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: uems-db
          property: password

  - type: static
    name: uems-frontend
    env: node
    region: global
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        value: https://uems-backend-ci15.onrender.com
    plan: free

  - type: postgres
    name: uems-db
    version: "16"
    env: shared
    plan: free
