services:
  - type: web
    name: uems-backend
    env: java
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
    plan: free

  - type: static
    name: uems-frontend
    env: node
    region: global
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./dist
    plan: free

  - type: postgres
    name: uems-db
    version: "18"
    env: shared
    plan: free
